# PyTorch Tensor Operations

In [1]:
import torch

## Arithmetic Element-wise Operations

In [ ]:
a = torch.FloatTensor([[1, 2],
                       [3, 4]])
b = torch.FloatTensor([[2, 2],
                       [3, 3]])

In [ ]:
print(a + b)

In [ ]:
a - b

In [ ]:
a * b

In [ ]:
a / b

In [ ]:
a == b

In [ ]:
a != b

In [ ]:
a ** b

## Inplace Operations

In [ ]:
print(a)
print(a.mul(b))
print(a)
print(a.mul_(b))
print(a)

## Sum, Mean (Dimension Reducing Operations)

In [ ]:
x = torch.FloatTensor([[1, 2, 3],
                       [3, 4, 5]])
print(x)

In [ ]:
print(x.sum())
print(x.mean())

In [ ]:
print(x.sum(dim=0))
print(x.sum(dim=-1))
print(x.sum(dim=1))

## Broadcast in Operations

What we did before,

In [2]:
x = torch.FloatTensor([[1, 2, 3]])
y = torch.FloatTensor([[3, 6, 9]])

print(x.size())
print(y.size())

torch.Size([1, 3])
torch.Size([1, 3])


In [3]:
z = x + y
print(z)
print(z.size())

tensor([[ 4.,  8., 12.]])
torch.Size([1, 3])


Broadcast feature provides operations between different shape of tensors.

### Tensor + Scalar

In [4]:
x = torch.FloatTensor([[1, 2, 3],
                       [3, 6, 9]])
y = 1

print(x.size())

torch.Size([2, 3])


In [5]:
z = x + y
print(z)
print(z.size())

tensor([[ 2.,  3.,  4.],
        [ 4.,  7., 10.]])
torch.Size([2, 3])


### Tensor + Vector

In [6]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 8, 12]])
y = torch.FloatTensor([[3,
                       6,
                       9]])
k = torch.FloatTensor( [ [5],
                         [7]  ])
print(x.size())
print(y.size())
print(k.size())

torch.Size([2, 3])
torch.Size([1, 3])
torch.Size([2, 1])


In [7]:
z = x + y
print(z)
print(z.size())
z = x + k
print(z)
print(z.size())
z = y + k
print(z)
print(z.size())

tensor([[ 4.,  8., 12.],
        [ 7., 14., 21.]])
torch.Size([2, 3])
tensor([[ 6.,  7.,  8.],
        [11., 15., 19.]])
torch.Size([2, 3])
tensor([[ 8., 11., 14.],
        [10., 13., 16.]])
torch.Size([2, 3])


In [ ]:
x = torch.FloatTensor([[[1, 2]]])
y = torch.FloatTensor([3,
                       5])

print(x.size())
print(y.size())

In [ ]:
z = x + y
print(z)
print(z.size())

### Tensor + Tensor

In [ ]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3],
                       [5]])

print(x.size())
print(y.size())

In [ ]:
z = x + y
print(z)
print(z.size())

Note that you need to be careful before using broadcast feature.

### Failure Case

In [ ]:
x = torch.FloatTensor([[[1, 2],
                        [4, 8]]])
y = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print(x.size())
print(y.size())

z = x + y

### JOE TEST

In [ ]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 8, 9]])
y = torch.FloatTensor([3,5])
z = torch.FloatTensor([[7,9]])
print(x)
print(y)
print(z)
print(x.size())
print(y.size())
print(z.size())