# PyTorch Tensor Operations

In [1]:
import torch

## Arithmetic Element-wise Operations

In [2]:
a = torch.FloatTensor([[1, 2],
                       [3, 4]])
b = torch.FloatTensor([[2, 2],
                       [3, 3]])

In [7]:
print(a + b)

tensor([[3., 4.],
        [6., 7.]])


In [8]:
a - b

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [10]:
a * b

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [11]:
a / b

tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])

In [12]:
a == b

tensor([[False,  True],
        [ True, False]])

In [15]:
a != b

tensor([[ True, False],
        [False,  True]])

In [14]:
a ** b

tensor([[ 1.,  4.],
        [27., 64.]])

## Inplace Operations

In [16]:
print(a)
print(a.mul(b))
print(a)
print(a.mul_(b))
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


## Sum, Mean (Dimension Reducing Operations)

In [42]:
x = torch.FloatTensor([[1, 2, 3],
                       [3, 4, 5]])
print(x)

tensor([[1., 2., 3.],
        [3., 4., 5.]])


In [43]:
print(x.sum())
print(x.mean())

tensor(18.)
tensor(3.)


In [44]:
print(x.sum(dim=0))
print(x.sum(dim=-1))
print(x.sum(dim=1))

tensor([4., 6., 8.])
tensor([ 6., 12.])
tensor([ 6., 12.])


## Broadcast in Operations

What we did before,

In [45]:
x = torch.FloatTensor([[1, 2, 3]])
y = torch.FloatTensor([[3, 6, 9]])

print(x.size())
print(y.size())

torch.Size([1, 3])
torch.Size([1, 3])


In [46]:
z = x + y
print(z)
print(z.size())

tensor([[ 4.,  8., 12.]])
torch.Size([1, 3])


Broadcast feature provides operations between different shape of tensors.

### Tensor + Scalar

In [47]:
x = torch.FloatTensor([[1, 2, 3],
                       [3, 6, 9]])
y = 1

print(x.size())

torch.Size([2, 3])


In [48]:
z = x + y
print(z)
print(z.size())

tensor([[ 2.,  3.,  4.],
        [ 4.,  7., 10.]])
torch.Size([2, 3])


### Tensor + Vector

In [63]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 8, 12]])
y = torch.FloatTensor([[3,
                       6,
                       9]])
k = torch.FloatTensor( [ [5],
                         [7]  ])
print(x.size())
print(y.size())
print(k.size())

torch.Size([2, 3])
torch.Size([1, 3])
torch.Size([2, 1])


In [62]:
z = x + y
print(z)
print(z.size())
z = x + k
print(z)
print(z.size())
z = y + k
print(z)
print(z.size())

tensor([[ 4.,  8., 12.],
        [ 7., 14., 21.]])
torch.Size([2, 3])
tensor([[ 6.,  7.,  8.],
        [11., 15., 19.]])
torch.Size([2, 3])
tensor([[ 8., 11., 14.],
        [10., 13., 16.]])
torch.Size([2, 3])


In [64]:
x = torch.FloatTensor([[[1, 2]]])
y = torch.FloatTensor([3,
                       5])

print(x.size())
print(y.size())

torch.Size([1, 1, 2])
torch.Size([2])


In [65]:
z = x + y
print(z)
print(z.size())

tensor([[[4., 7.]]])
torch.Size([1, 1, 2])


### Tensor + Tensor

In [66]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3],
                       [5]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([2, 1])


In [68]:
z = x + y
print(z)
print(z.size())

tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


Note that you need to be careful before using broadcast feature.

### Failure Case

In [69]:
x = torch.FloatTensor([[[1, 2],
                        [4, 8]]])
y = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print(x.size())
print(y.size())

z = x + y

torch.Size([1, 2, 2])
torch.Size([3, 3])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

### JOE TEST

In [33]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 8, 9]])
y = torch.FloatTensor([3,5])
z = torch.FloatTensor([[7,9]])
print(x)
print(y)
print(z)
print(x.size())
print(y.size())
print(z.size())

tensor([[1., 2., 3.],
        [4., 8., 9.]])
tensor([3., 5.])
tensor([[7., 9.]])
torch.Size([2, 3])
torch.Size([2])
torch.Size([1, 2])
