# PyTorch Tensor

In [2]:
import torch

In [3]:
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
lt = torch.LongTensor([[1, 2],
                       [3, 4]])
lt

In [ ]:
bt = torch.ByteTensor([[1, 0],
                       [0, 1]])
bt

In [ ]:
x = torch.FloatTensor(3, 2)
x

In [4]:
y = torch.LongTensor(2,3,4)
print(y)
print(y.size())
print(y.shape)

tensor([[[                   0,                    0,                  255,
                             0],
         [                   0,                    0,                    0,
                             0],
         [                   0,                    0,                    0,
                             0]],

        [[-5764598749776197196,  3458773287078580016,                    8,
                             0],
         [                   0,                    0,                    0,
                             0],
         [                   0,                    0,                    0,
                             0]]])
torch.Size([2, 3, 4])
torch.Size([2, 3, 4])


### NumPy Compatibility

In [5]:
import numpy as np

# Define numpy array.
x = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print(x, type(x))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>


In [ ]:
x = torch.from_numpy(x)
print(x, type(x))

In [ ]:
x = x.numpy()
print(x, type(x))

### Tensor Type-casting

In [ ]:
ft.long()

In [ ]:
lt.float()

In [ ]:
torch.FloatTensor([1, 0]).byte()

### Get Shape

In [11]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])
y = torch.FloatTensor([[1],[2]])
z = torch.FloatTensor([1,2])

##### - Get tensor shape.

In [12]:
print(x.size())
print(x.shape)
print(y.size())
print(z.size())

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])
torch.Size([2, 1])
torch.Size([2])


##### - Get number of dimensions in the tensor.

In [13]:
print(x.dim())
print(len(x.size()))

3
3


##### - Get number of elements in certain dimension of the tensor.

In [20]:
print(x.size(0))
print(x.shape[-1])

3
2


##### - Get number of elements in the last dimension.

In [ ]:
print(x.size(-1))
print(x.shape[-1])