## PyTorch Tensor Slicing and Concatenation

In [1]:
import torch

## Slicing and Concatenation

### Indexing and Slicing

Prepare target tensor.

In [2]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])
print(x.size())

torch.Size([3, 2, 2])


Access to certain dimension.

In [4]:
print(x[0])
print(x[0, :])
print(x[0, :, :])

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])


In [4]:
print(x[-1])
print(x[-1, :])
print(x[-1, :, :])

tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])


In [5]:
print(x[:, 0, :])
print(x[:, :, 1])

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])
tensor([[ 2.,  4.],
        [ 6.,  8.],
        [10., 12.]])


Access by range. Note that the number of dimensions would not be changed.

In [9]:
print(x[1:3, :, :].size())
print(x[0:2, :, :].size())
print(x[0:3, :, :].size())
print(x[:, :1, :].size())
print(x[:, :-1, :].size())

torch.Size([2, 2, 2])
torch.Size([3, 2, 2])
torch.Size([3, 1, 2])
torch.Size([3, 1, 2])


### split: Split tensor to desirable shapes.

In [16]:
x = torch.FloatTensor(10, 4)
print(x)

tensor([[-7.4804e-06,  4.5863e-41, -5.7232e-06,  4.5863e-41],
        [-7.4847e-06,  4.5863e-41, -5.7238e-06,  4.5863e-41],
        [-3.8962e-09,  4.5863e-41, -3.8959e-09,  4.5863e-41],
        [-1.1433e-06,  4.5863e-41, -7.4982e-06,  4.5863e-41],
        [-7.4972e-06,  4.5863e-41, -7.4848e-06,  4.5863e-41],
        [-7.4852e-06,  4.5863e-41, -7.4847e-06,  4.5863e-41],
        [-7.4620e-06,  4.5863e-41, -7.4986e-06,  4.5863e-41],
        [-7.4983e-06,  4.5863e-41, -7.4629e-06,  4.5863e-41],
        [-7.4989e-06,  4.5863e-41, -7.4982e-06,  4.5863e-41],
        [-7.4978e-06,  4.5863e-41, -7.4636e-06,  4.5863e-41]])


In [17]:
splits = x.split(4, dim=0)
print(splits)
for s in splits:
    print(s.size())

(tensor([[-7.4804e-06,  4.5863e-41, -5.7232e-06,  4.5863e-41],
        [-7.4847e-06,  4.5863e-41, -5.7238e-06,  4.5863e-41],
        [-3.8962e-09,  4.5863e-41, -3.8959e-09,  4.5863e-41],
        [-1.1433e-06,  4.5863e-41, -7.4982e-06,  4.5863e-41]]), tensor([[-7.4972e-06,  4.5863e-41, -7.4848e-06,  4.5863e-41],
        [-7.4852e-06,  4.5863e-41, -7.4847e-06,  4.5863e-41],
        [-7.4620e-06,  4.5863e-41, -7.4986e-06,  4.5863e-41],
        [-7.4983e-06,  4.5863e-41, -7.4629e-06,  4.5863e-41]]), tensor([[-7.4989e-06,  4.5863e-41, -7.4982e-06,  4.5863e-41],
        [-7.4978e-06,  4.5863e-41, -7.4636e-06,  4.5863e-41]]))
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


### chunk: Split tensor to number of chunks.

In [9]:
x = torch.FloatTensor(8, 4)

In [10]:
chunks = x.chunk(3, dim=0)

for c in chunks:
    print(c.size())

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([2, 4])


### index_select: Select elements by using dimension index.

In [11]:
x = torch.FloatTensor([[[1, 1],
                        [2, 2]],
                       [[3, 3],
                        [4, 4]],
                       [[5, 5],
                        [6, 6]]])
indice = torch.LongTensor([2, 1])

print(x.size())

torch.Size([3, 2, 2])


In [12]:
y = x.index_select(dim=0, index=indice)

print(y)
print(y.size())

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])
torch.Size([2, 2, 2])


### cat: Concatenation of multiple tensors in the list.

In [13]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12],
                       [13, 14, 15],
                       [16, 17, 18]])

print(x.size(), y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [14]:
z = torch.cat([x, y], dim=0)
print(z)
print(z.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
torch.Size([6, 3])


In [15]:
z = torch.cat([x, y], dim=-1)
print(z)
print(z.size())

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


### stack: Stacking of multiple tensors in the list.

In [16]:
z = torch.stack([x, y])
print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


Or you can specify the dimension. Default is 0.

In [17]:
z = torch.stack([x, y], dim=-1)
print(z)
print(z.size())

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])
torch.Size([3, 3, 2])


### Implement 'stack' function by using 'cat'.

In [18]:
# z = torch.stack([x, y])
z = torch.cat([x.unsqueeze(0), y.unsqueeze(0)], dim=0)
print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


### Useful Trick: Merge results from iterations

In [19]:
result = []
for i in range(5):
    x = torch.FloatTensor(2, 2)
    result += [x]

result = torch.stack(result)
result.size()

torch.Size([5, 2, 2])